# Generated by Django 5.2 on 2025-04-24 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Security', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='profile_picture_url',
            field=models.URLField(blank=True, default='/_uploads/profiles/default/avatar.png', null=True),
        ),
    ]
