# Generated by Django 5.2 on 2025-04-24 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Security', '0002_alter_customuser_profile_picture_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='profession',
            field=models.CharField(default=None, max_length=50, null=True),
        ),
    ]
